name: 'issue2md'
author: 'sxy15'
description: 'issue2md'

branding:
  icon: 'battery'
  color: 'blue'

on:
  issues:
    types: [opened, edited, closed, reopened]
  issue_comment:
    types: [created, edited, deleted]

inputs:
  token:
    description: 'GitHub token'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
