name: build test

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: set node version
              uses: actions/setup-node@v2
              with:
                  node-version: 20.9.0
            - uses: actions/checkout@v3
            - name: install dependencies
              run: pnpm i
            - name: build
              run: npm run build
    
    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v3
            - uses: /action.yml
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
