name: Test issue2md action

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test issue2md action
        uses: ./
        with:
          branch: 'main'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}